import type { Metadata } from "next";
import type { SiteSettings } from "@/lib/data/site-settings";
import { SITE_URL } from "@/lib/site-url";

// Everything that decides what X, WhatsApp, LinkedIn, Slack, iMessage & co show
// when a mjfird.com link is pasted. All of it is editable under
// /admin/settings → "Link preview".

// The branded card generated by src/app/opengraph-image.tsx. We point at it
// explicitly instead of letting the file convention inject the tag, because the
// URL needs to carry a version: social platforms cache previews by image URL, so
// a re-scrape of an unchanged URL would keep serving the old thumbnail for days
// after the admin changed it.
const SHARE_CARD_PATH = "/opengraph-image";

/** "@mjfird" from "mjfird", "@mjfird", or a full x.com profile URL. */
export function formatSocialHandle(raw: string) {
  const handle = raw.trim().replace(/^https?:\/\/(www\.)?(x|twitter)\.com\//i, "").replace(/^@/, "");
  return handle ? `@${handle.replace(/\/.*$/, "")}` : "";
}

/** Long titles get smaller type rather than overflowing the 1200×630 card. */
export function shareHeadlineSize(headline: string) {
  if (headline.length <= 10) return 116;
  if (headline.length <= 20) return 88;
  if (headline.length <= 34) return 68;
  if (headline.length <= 60) return 52;
  return 42;
}

export function shareCardEyebrow(settings: SiteSettings) {
  return settings.shareCardEyebrow || settings.heroEyebrow;
}

export function shareCardHeadline(settings: SiteSettings) {
  return settings.shareCardHeadline || settings.logoText || settings.siteTitle;
}

export function shareTitle(settings: SiteSettings) {
  return settings.shareTitle || settings.siteTitle;
}

export function shareDescription(settings: SiteSettings) {
  return settings.shareDescription || settings.siteDescription;
}

/** Changes whenever settings are saved, so platforms re-fetch the thumbnail. */
function cardVersion(settings: SiteSettings) {
  const stamp = Date.parse(settings.updatedAt);
  return Number.isNaN(stamp) ? "1" : stamp.toString(36);
}

export function shareImage(settings: SiteSettings): NonNullable<Metadata["openGraph"]>["images"] {
  const alt = shareTitle(settings);

  // An uploaded image is served as-is: re-encoding it would only cost quality
  // and file size, and the admin is told to upload it at 1200×630.
  if (settings.shareImageMode === "custom" && settings.shareImageUrl) {
    return [{ url: settings.shareImageUrl, alt }];
  }

  return [
    {
      url: `${SITE_URL}${SHARE_CARD_PATH}?v=${cardVersion(settings)}`,
      width: 1200,
      height: 630,
      type: "image/png",
      alt,
    },
  ];
}

/**
 * Site-wide Open Graph + X card metadata. Pages deeper in the tree inherit this
 * and can override `openGraph.images` (a project or post with its own share
 * image does exactly that) — Next mirrors the resolved OG image onto the X card,
 * so each route keeps the right thumbnail on every platform.
 */
export function shareMetadata(settings: SiteSettings): Metadata {
  const handle = formatSocialHandle(settings.shareTwitterHandle);

  return {
    openGraph: {
      type: "website",
      siteName: settings.logoText || settings.siteTitle,
      title: shareTitle(settings),
      description: shareDescription(settings),
      locale: "en_US",
      images: shareImage(settings),
    },
    // Deliberately no title/description/images here: Next fills those in per
    // route from the resolved Open Graph tags, so a project or post shared on X
    // shows its own card instead of the site-wide one.
    twitter: {
      card: "summary_large_image",
      ...(handle && { site: handle, creator: handle }),
    },
  };
}
